import {
	Box,
	Button,
	Container,
	Heading,
	VStack,
	chakra,
} from "@chakra-ui/react";
import html2canvas from "html2canvas";
import type { NextPage } from "next";
import Head from "next/head";

const Div = chakra("div");

const Home: NextPage = () => {
	const saveAsImage = (url: string) => {
		const downloadLink = document.createElement("a");
		if (typeof downloadLink.download === "string") {
			downloadLink.href = url;
			downloadLink.download = "letter.png";
			document.body.appendChild(downloadLink);
			downloadLink.click();
			document.body.removeChild(downloadLink);
		} else {
			window.open(url);
		}
	};
	const onClickSaveEvent = () => {
		const target = document.getElementById("letter");
		if (!target) return;
		html2canvas(target, {
			scale: 2,
		}).then((canvas) => {
			const targetImageUrl = canvas.toDataURL("img/png");
			saveAsImage(targetImageUrl);
		});
	};

	const placeholder = `
メッセージだけでは伝わらない、　　　　
ちょっといい手紙を書きましょう。　　　
この枠の中に手紙を書いてください。　　
思うままに書いたら「保存する」ボタン。
伝えたい人に送るもよし。　　　　　　　
自分のカメラロールにそっとしまうもよし。
あなたの好きなように使ってください。`;

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Container h="100vh">
				<VStack spacing="12" h="100%" justify={"center"}>
					<Box textAlign={"center"}>
						<Heading color="teal.700">Web手紙</Heading>
					</Box>
					<Div
						id="letter"
						contentEditable
						overflow="hidden"
						w="520px"
						h="520px"
						p="20px"
						fontSize="24px"
						lineHeight="40px"
						boxShadow="base"
						spellCheck={false}
						style={{
							background: `linear-gradient(
                  180deg,
                  rgba(0,0,0,0) 0%,
                  rgba(0,0,0,0) 96%,
                  #eee 96%,
                  #eee 100%)`,
							backgroundSize: "100% 40px",
							backgroundPosition: "20px 20px",
						}}
						_focus={{
							outline: "none",
						}}
					>
						{placeholder}
					</Div>
					<Box textAlign={"center"}>
						<Button
							onClick={() => onClickSaveEvent()}
							variant={"outline"}
							colorScheme="teal"
						>
							保存する
						</Button>
					</Box>
				</VStack>
			</Container>
		</>
	);
};

export default Home;
